### ISSUE TITLE
Run errror: run.py

### ISSUE THREAD

**Issue by ShinkuKira21** [Tauseef-Hilal/Pathfinding-Visualizer#2]
**Command:** python3 run.py

```py
pygame 2.1.2 (SDL 2.0.16, Python 3.9.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "..../Pathfinding-Visualizer/run.py", line 1, in <module>
    from src.main import main
  File "..../Pathfinding-Visualizer/src/main.py", line 4, in <module>
    from src.state import State
  File "..../Pathfinding-Visualizer/src/state.py", line 2, in <module>
    from src.widgets import Label
  File "..../Pathfinding-Visualizer/src/widgets.py", line 308
    match child.alignment:
          ^
SyntaxError: invalid syntax
```

**Comment by ShinkuKira21** [comment]
In your documentation, state `Python >= 3.10` rather than `Python 3.x`. Match Statements are only supported on versions 3.10 and higher.

**Comment by Tauseef-Hilal** [comment]
Thanks! Had no idea about that. BTW, the animations are much better now, you should try the new version
